= Memoria Refactoring
:toc:

== Null Object en Color

. Aplicando el 'patrón' NULL object, añadimos un nuevo método en el enumerado *Color*.
Los test continúan en verde, puesto que no hemos hecho cambios que afecten a colaboradores.
https://github.com/juanaviladev/refactoring-draughts/commit/21f4de3f73798ea7601c0bd62d0fdb7b4c4d2e6c[Ver commit]

. Sustituimos los _return null_ que existen en el código para que devuelvan la nueva constante *NULL*
del enumerado. Hemos roto las pruebas de aquellos casos que evaluaban el caso de coordenadas fuera del tablero.
https://github.com/juanaviladev/refactoring-draughts/commit/aa080085fdd9e5a35697347746307087d6d2a288[Ver commit]

. Corregimos los casos de prueba con la nueva constante *NULL*
https://github.com/juanaviladev/refactoring-draughts/commit/898fdcb6e8c3c77054dbcc334dc77b8a82a419c9[Ver commit]

. Finalmente, refactorizamos aquellos métodos de colaboradores en los que se hace la comparación color != null ó color == null por
el nuevo método *isNull()*. Todas las pruebas siguen en verde, no ha habido cambios que afecten a los input/output de
las clases (caja negra).
.. https://github.com/juanaviladev/refactoring-draughts/commit/4845d05d249bc150e01eadc1b02a1d004aa4cd2b[Ver commit]
.. https://github.com/juanaviladev/refactoring-draughts/commit/4845d05d249bc150e01eadc1b02a1d004aa4cd2b[Ver commit]

== Chain of responsability sobre Game

. Planteamos un borrador del diseño al que queremos llegar

[plantuml, ,svg]
----
top to bottom direction

class Game
Game ..> Movement
Game ..> EmptyOriginChecker
Game ..> NotEmptyTargetChecker
Game ..> IsPlayerPieceChecker

class Movement {
    Movement(Coordinate origin,
    Coordinate target)
}

interface LegalMovementChecker {
    + check(Movement)
}
LegalMovementChecker ..> Movement

class EmptyOriginChecker {}
LegalMovementChecker <|.. EmptyOriginChecker
EmptyOriginChecker ..> Movement
EmptyOriginChecker --> LegalMovementChecker

class NotEmptyTargetChecker {}
LegalMovementChecker <|.. NotEmptyTargetChecker
NotEmptyTargetChecker ..> Movement
NotEmptyTargetChecker --> LegalMovementChecker

class IsPlayerPieceChecker {}
LegalMovementChecker <|.. IsPlayerPieceChecker
IsPlayerPieceChecker ..> Movement
IsPlayerPieceChecker --> LegalMovementChecker

note bottom of IsPlayerPieceChecker: OPPOSITE_PIECE
----

. Desplazamos una de las ramas condicionales a la clase _EmptyOriginChecker_. Es una aplicación
de _Replace Method with Method Object_. No hemos roto ningun test puesto que el comportamiento de Game sigue siendo exactamente el mismo.
https://github.com/juanaviladev/refactoring-draughts/commit/590186ee07b948ceb6331154af48fc614bf38939[Ver commit]

. Repetimos el paso anterior para el resto de ramas condicionales.
https://github.com/juanaviladev/refactoring-draughts/commit/25bc1fd1c0e45972437a1f9cc9abb66e8647ded5[Ver commit]

. Como tenemos múltiples clases que comparten interfaz pública, extraemos el método aplicando _Extract Interface_.
Las pruebas siguen en verde.
https://github.com/juanaviladev/refactoring-draughts/commit/d9a82d1d7cf8953b8b74ca724580b36448500d0e[Ver commit]

. Tenemos código duplicado en la clase Game, en lo relativo al uso de los distintos _LegalMovementChecker_.
En este caso vamos a replantear el método que utiliza los checker para que sea más simple y eliminar el código repetido.
Las pruebas siguen en verde.
https://github.com/juanaviladev/refactoring-draughts/commit/61e6878b647cebb934b694d1cef720b4f18af135[Ver commit]

. Separamos la creación de los checkers de su uso, para mejorar la legibilidad y su mantenibilidad.
Las pruebas siguen en verde.
https://github.com/juanaviladev/refactoring-draughts/commit/46407f468e2dc3cfa311c8e0099f22f9c6c918d2[Ver commit]

. No todos los checker utilizan los mismos colaboradores, para evitar acoplar a todos con colaboradores que quizás no usen,
vamos a desplazar los parámetros no comunes a atributos de clase.
Las pruebas siguen en verde.
https://github.com/juanaviladev/refactoring-draughts/commit/bfdfe645f24431157d3149d6447d5a8e35983bdf[Ver commit]

. El par _int pair, Coordinate... coordinates_ se repite como grupo de parámetros en varios métodos,
parece ser un grupo cohesivo de parámetros, creamos una nueva clase que lo representa (Parameter Object): Jugada
https://github.com/juanaviladev/refactoring-draughts/commit/fc2e992f599b269f99a8dd0af6a721fe097597ad[Ver commit]

. Ahora es necesario actualizar todos los colaboradores para que usen la nueva clase _Move_, sustituyendo
el anterior par de parámetros. Algunas pruebas se han visto afectadas por el cambio en las interfaces de los métodos.
https://github.com/juanaviladev/refactoring-draughts/commit/38475c278a864c20ea727fd8c10d562b14b377ad[Ver commit]

. Al extraer la nueva clase _Move_, parece representar más bien un origen->destino dentro de una jugada (es decir, un par de la jugada).
La jugada podría verse mejor como un contenedor de pares (de hecho, el método _isCorrectPairMove_ de Game nos da una pista clara).
Mantenemos la clase _Move_ para contener los pares origen -> destino.
https://github.com/juanaviladev/refactoring-draughts/commit/6c2feaa4c5151765c1083b1146522907e330f9b8[Ver commit]

. Los checker deberían ser los responsables de delegar al siguiente o finalizar la cadena si han detectado un error, movemos esa responsabilidad desde la clase Game.
https://github.com/juanaviladev/refactoring-draughts/commit/c796e65cf46875e2d1bd4fbd0c075c27e0b66848[Ver commit]

. La lógica de delegar en el siguiente de la cadena o devolver null está duplicada en todos los checker, convertimos la interfaz
_LegalMovementChecker_ en clase abstracta para compartir el comportamiento (Extract superclass).
https://github.com/juanaviladev/refactoring-draughts/commit/c796e65cf46875e2d1bd4fbd0c075c27e0b66848[Ver commit]

== Unir N vistas

. De todas las vistas, _ResumeView_ es la que menos dependencias aferentes tiene, comenzamos por ella para evitar
la inestabilidad. La fusionamos con _View_. También fusionamos las pruebas, que se han roto al desaparecer la vista _ResumeView_.
https://github.com/juanaviladev/refactoring-draughts/commit/654f598e6ea3550708a20fed90e8527fd7ce6c75[Ver commit]

. Continuamos con _StartView_. Y convertimos _View_ en subclase de _SubView_ para poder utilizar la consola.
https://github.com/juanaviladev/refactoring-draughts/commit/20f4431023b96cdbdbefea389a51b981c5b51d1e[Ver commit]

. Continuamos con _PlayView_.
https://github.com/juanaviladev/refactoring-draughts/commit/d46decf054f1e3418bad49cffa77a2a4df863d3e[Ver commit]

. Continuamos con _GameView_.
https://github.com/juanaviladev/refactoring-draughts/commit/e4bd0c126499817a202889bd0fd7eb5650ce13b5[Ver commit]

. Eliminamos _SubView_, puesto que solamente tenemos una subclase (_View_), ya no tiene sentido al unir todas las vistas en 1.
https://github.com/juanaviladev/refactoring-draughts/commit/5b890881b049431b7b49308b78ffcb1d950e3456[Ver commit]
